catch error when user doesn't provide a prefix
andrenarchy/libfulltext pull request #22
Opened 2017-12-29 23:09 UTC by pseyfert

the executable just crashed for me because I forgot the prefix. Guess there's not much we can do at that point, but there should be a clear'ish error message at least.

2017-12-29 23:12 UTC, mfherbst requested changes

2017-12-29 23:12 UTC, mfherbst commented on libfulltext/fulltext.py
> -    prefix, identifier = prefixed_identifier.split(':', 1)
I think this is more clear:
```py
if ":" not in prefixed_identifier:
    raise ValueError("No prefix provided")
prefix, identifier = prefixed_identifier.split(":", 1)
```

2017-12-29 23:12 UTC, pseyfert commented on libfulltext/fulltext.py
> -    prefix, identifier = prefixed_identifier.split(':', 1)
agree

2017-12-30 08:17 UTC, mfherbst approved these changes

2017-12-30 11:09 UTC, merged